channels:
  - r
  - conda-forge
  - defaults
dependencies:
  - r-base
  - r-dplyr
  - r-tidyr
  - r-purrr
  - r-readr
  - r-stringr
  - r-dbplyr
  - r-magrittr
  - r-xml2
  - r-rvest
  - r-httr
  - r-rsqlite
