name: tidyverse
channels:
  - r
  - conda-forge
  - defaults
dependencies:
  - r-base
  - r-tidyverse
  - r-tidyr=0.8.1
  - r-purrr=0.2.5
  - r-dbplyr
  - r-magrittr
  - r-xml2
  - r-rvest
  - r-httr
  - r-rsqlite
  - r-dt
  - r-formattable
  - r-rmarkdown=1.10
  - pandoc=2.3
